export const seriesCards = [
  {
    index: "01",
    title: "PSR Series",
    copy: "Our PSR series automates pallet stacking, pallet transport, and trolley movement for warehouse automation for improved inventory visibility, operational efficiency, productivity, and intralogistics performance.",
    tags: ["Stacking", "G2G"],
    backgroundImage: "psr-main.png",
    image: "psr-2000-r.png",
    href: "/psr-series",
    marker: "PSR",
    featured: true,
  },
  {
    index: "02",
    title: "AR Series",
    copy: "Our AR Series automates diverse applications through one platform and multiple top modules.",
    tags: ["Tugging", "Lifting", "Tunneling"],
    backgroundImage: "PSR-Series.jpg",
    image: "bcbedcb1052074b00bb60d9f0fe5e0bb_60ea9badfafa109779007ff36fd0cf87881840a1-p-1080.png",
    href: "/ar-series",
    marker: "AR",
    featured: false,
  },
  {
    index: "03",
    title: "AGV Series",
    copy: "Our AGV Series streamlines point-to-point material transport through compact, QR-guided automation.",
    tags: ["Lifting", "Sorting"],
    backgroundImage: "AGV.jpg",
    image: "agv-100-new-p-500.png",
    href: "/agv-series",
    marker: "AGV",
    featured: false,  
  },
];
