const solutionsPath = "/anscer/images/solutions/";
const workflowPath = `${solutionsPath}workflow-automation/`;
const automationPath = `${solutionsPath}automation-designed/`;

export const solutionHighlights = [
  { icon: `${automationPath}engineer-icon.svg`, title: "Engineered In India", copy: "Built For Global Standards" },
  { icon: `${automationPath}throughput-icon.svg`, title: "24/7 Throughput", copy: "Continuous Autonomous Cycles" },
  { icon: `${automationPath}safety-icon.svg`, title: "Safety Certified", copy: "Sensor-Fused Obstacle Avoidance" },
  { icon: `${automationPath}support-icon.svg`, title: "In-House Support", copy: "Deployment To Maintenance" },
];

export const workflowSteps = [
  {
    title: "Requirement Capture",
    copy: "Translate operational requirements into a structured automation blueprint. We map workflows, constraints, movement patterns, infrastructure, and performance goals to define the right automation approach.",
    image: `${workflowPath}image-1.png`,
    icon: `${workflowPath}icon-1.svg`,
  },
  {
    title: "Simulation",
    copy: "Model real-world workflows in a controlled environment to validate robot movements, task flows, fleet behavior, and system interactions before deployment begins.",
    image: `${workflowPath}image-2.png`,
    icon: `${workflowPath}icon-2.svg`,
  },
  {
    title: "Optimization",
    copy: "Identify the most effective automation strategy by refining routes, fleet configurations, task allocation, and workflow parameters to maximize throughput and resource utilization.",
    image: `${workflowPath}image-3.png`,
    icon: `${workflowPath}icon-3.svg`,
  },
  {
    title: "Analysis & Reporting",
    copy: "Turn operational data into actionable insights with detailed analysis and reporting that reveal bottlenecks, validate performance, and guide informed automation decisions.",
    image: `${workflowPath}image-4.png`,
    icon: `${workflowPath}icon-4.svg`,
  },
];

export const automationSolutions = [
  {
    title: "Warehouse Solutions",
    copy: "From case picking and put away to cross docking, replenishment, and point-to-point transport, ANSCER automates critical warehouse workflows with its PSR and AR Series robots. Designed for continuous, autonomous operation, these solutions reduce manual handling, minimize forklift dependency, streamline warehouse flow, and enable operations to scale efficiently with changing throughput demands.",
    icon: `${automationPath}icon-1.svg`,
    image: `${automationPath}image-1.jpg`,
    imageAlt: "Autonomous forklift moving a pallet through warehouse racking",
    href: "/contact-us",
  },
  {
    title: "Manufacturing Solutions",
    copy: "From line-side delivery and WIP transport to finished-goods movement, ANSCER automates critical manufacturing workflows with its AR Series and LBR robots. Designed for continuous production support, these solutions enable timely material replenishment, reduce manual transport and forklift dependency, improve shop-floor safety, and maintain consistent material flow across production lines, assembly stations, and operational zones.",
    icon: `${automationPath}icon-2.svg`,
    image: `${automationPath}image-2.jpg`,
    imageAlt: "Engineer working at a manufacturing assembly station",
    href: "/contact-us",
  },
];

export type Workflow = {
  id: string;
  label: string;
  title: string;
  copy: string;
  robots: { name: string; image: string }[];
  steps: { title: string; copy: string }[];
  href: string;
};

export type MapMarker = { x: number; y: number };

const arSeries = { name: "AR series", image: `${solutionsPath}ar-series.png` };

export const workflowMapImage = `${solutionsPath}warehouse-workflow.png`;

// Final copy is only available for the first tab of each section, so the
// remaining tabs reuse it with their own title until content is provided.
function withPlaceholders(
  base: Omit<Workflow, "id" | "label" | "title">,
  first: Pick<Workflow, "id" | "label" | "title">,
  rest: Pick<Workflow, "id" | "label">[],
): Workflow[] {
  return [
    { ...base, ...first },
    ...rest.map((tab) => ({ ...base, ...tab, title: tab.label })),
  ];
}

const casePicking = {
  copy: "Case-picking automation works best when robotic movement becomes part of the warehouse's existing execution process rather than operating as an isolated transport activity.",
  robots: [arSeries],
  steps: [
    {
      title: "Task Generation",
      copy: "Picking or transport tasks are generated by the warehouse management or control system according to the operational requirement.",
    },
    {
      title: "Case Handover",
      copy: "Once the required case or pallet is ready, the load is transferred to the robot through the defined loading process.",
    },
    {
      title: "Autonomous Movement",
      copy: "The robot receives its task and navigates through the facility while responding to obstacles, traffic and changing operating conditions.",
    },
    {
      title: "Destination Delivery",
      copy: "The load is transported to its designated destination, such as staging, dispatch, another work area or a production point.",
    },
    {
      title: "Task Completion",
      copy: "Task status is communicated back to the connected system, creating visibility across the movement workflow and enabling the next task to be assigned.",
    },
    {
      title: "Continuous Operation",
      copy: "The robot becomes part of a repeatable material-flow cycle, allowing case movement to continue without relying on operators for every transport journey.",
    },
  ],
  href: "/contact-us",
};

const putAway: Workflow = {
  id: "put-away",
  label: "Put away",
  title: "Put Away",
  copy: "Automated put away becomes more effective when robotic movement is integrated with the warehouse's existing execution systems.",
  robots: [arSeries],
  steps: [
    {
      title: "Task Generation",
      copy: "Put away tasks are generated by the WMS or warehouse control system based on inbound inventory and available storage locations.",
    },
    {
      title: "Material Handover",
      copy: "Pallets, bins or other materials are transferred from the receiving or inbound staging area to the robot through the defined loading process.",
    },
    {
      title: "Autonomous Navigation",
      copy: "The robot receives its destination and navigates through the warehouse while responding to obstacles, traffic and changing operating conditions.",
    },
    {
      title: "Storage Delivery",
      copy: "The material is transported to its assigned destination, such as a floor storage position, rack, buffer area or downstream operational zone.",
    },
    {
      title: "Put Away Completion",
      copy: "The robot completes the assigned movement and communicates task status to the connected warehouse system.",
    },
    {
      title: "Inventory Visibility",
      copy: "Location and task information is updated, providing greater visibility into where inventory has been placed and enabling the next warehouse task to be assigned.",
    },
  ],
  href: "/contact-us",
};

const [casePickingTab, ...warehousePlaceholders] = withPlaceholders(
  casePicking,
  { id: "case-picking", label: "Case Picking", title: "Case Picking" },
  [
    { id: "cross-docking", label: "Cross-Docking" },
    { id: "point-to-point", label: "Point-to-Point Transfer" },
    { id: "finished-goods", label: "Finished goods movement" },
    { id: "work-in-progress", label: "Work in progress movement" },
  ],
);

export const warehouseWorkflows: Workflow[] = [
  casePickingTab,
  putAway,
  ...warehousePlaceholders,
];

// Step marker positions as % of the (square) workflow map image.
export const warehouseMapMarkers: MapMarker[] = [
  { x: 12.5, y: 68 },
  { x: 7.5, y: 60 },
  { x: 12, y: 15 },
  { x: 50, y: 5 },
  { x: 83, y: 13 },
  { x: 90, y: 55 },
];

export const manufacturingWorkflows = withPlaceholders(
  {
    copy: "Line-side replenishment refers to the process of delivering raw materials, components, kits, or consumables from storage or supermarkets to production lines and workstations to maintain uninterrupted manufacturing operations. It ensures operators receive the right materials at the right time and in the required quantities.",
    robots: [arSeries],
    steps: [
      {
        title: "Replenishment task is received",
        copy: "The warehouse system sends the picking task based on the customer order and required cases.",
      },
      {
        title: "AMR moves to the storage area",
        copy: "The AMR autonomously navigates to the assigned picking location.",
      },
      {
        title: "Materials are picked and loaded",
        copy: "Workers pick the required full cases from storage and load them onto the AMR.",
      },
      {
        title: "AMR transports materials",
        copy: "The AMR follows an optimized route through the warehouse, reducing manual walking and avoiding congestion.",
      },
      {
        title: "Materials arrive at the line-side location",
        copy: "The AMR delivers the completed picks to the designated outbound staging or consolidation area.",
      },
      {
        title: "AMR starts the next task",
        copy: "After completing the delivery, the AMR receives its next assignment and returns to the pick zone.",
      },
    ],
    href: "/contact-us",
  },
  { id: "line-side", label: "Line-side replenishment", title: "Line-side replenishment" },
  [
    { id: "finished-goods", label: "Finished goods movement" },
    { id: "work-in-progress", label: "Work in progress transport" },
    { id: "pallet-handling", label: "Pallet handling" },
    { id: "machine-tending", label: "Machine tending" },
    { id: "waste-scrap", label: "Waste and scrap handling" },
  ],
);

export const manufacturingMapMarkers: MapMarker[] = [
  { x: 18, y: 95 },
  { x: 13, y: 88 },
  { x: 17.5, y: 23 },
  { x: 50, y: 6 },
  { x: 86, y: 17 },
  { x: 86, y: 77 },
];

const materialMovementPath = `${solutionsPath}material-movement/`;

export const materialMovementSeries = [
  {
    title: "PSR Series",
    copy: "Automates pallet stacking, transport, and trolley movement for efficient warehouse and intralogistics operations.",
    tags: ["Stacking", "G2G"],
    image: `${materialMovementPath}psr.png`,
    imageAlt: "PSR 2000 autonomous pallet stacker in a warehouse aisle",
    imagePosition: "object-[72%_center]",
    href: "/products/psr",
  },
  {
    title: "AR Series",
    copy: "Automates multiple material handling applications through a modular platform with interchangeable top modules.",
    tags: ["Tugging", "Lifting", "Tunneling"],
    image: `${materialMovementPath}ar.png`,
    imageAlt: "AR 250 autonomous mobile robot on a factory floor",
    imagePosition: "object-[65%_center]",
    href: "/products/ar",
  },
  {
    title: "AGV Series",
    copy: "Automates point-to-point material transport through compact, QR-guided navigation for efficient operations.",
    tags: ["Lifting", "Sorting"],
    image: `${materialMovementPath}agv.png`,
    imageAlt: "AGV 100 compact automated guided vehicle in a warehouse",
    imagePosition: "object-center",
    href: "/products/agv",
  },
];

const industriesPath = `${solutionsPath}automation-industries/`;
// Descriptions are placeholder copy from the design until final content is provided.
const shortCopy = "Lorem ipsum dolor sit amet, consecte lorem ipsum dolor sit amet, consecte";
const longCopy = "Lorem ipsum dolor sit amet, lorem ipsum dolor sit amet, consecte lorem ipsum dolor";

// Order matters: on large screens the grid auto-places these around the
// tall Automotive card in the middle column.
export const automationIndustries = [
  { title: "Pharmaceutical", copy: shortCopy, image: `${industriesPath}image-1.jpg` },
  { title: "Automotive", copy: shortCopy, image: `${industriesPath}automotive.jpg`, featured: true },
  { title: "Manufacturing", copy: longCopy, image: `${industriesPath}manufacturing.png` },
  { title: "FMCG", copy: shortCopy, image: `${industriesPath}fmcg.jpg` },
  { title: "Electronics", copy: shortCopy, image: `${industriesPath}electronics.jpg` },
  { title: "Food & Beverages", copy: longCopy, image: `${industriesPath}food-and-beverages.png` },
  { title: "White goods", copy: shortCopy, image: `${industriesPath}white-goods.jpg` },
  { title: "3PL", copy: shortCopy, image: `${industriesPath}3pl.png` },
];

const intelligentPath = `${solutionsPath}intelligent-automation/`;
const moduleCopy =
  "Interchangeable top modules adapt robots for diverse material handling requirements.";

// The second and third descriptions repeat the first in the design; replace
// when final copy is provided.
export const intelligentAutomationFeatures = [
  { title: "Flexible Module Design", copy: moduleCopy, icon: `${intelligentPath}icon-1.svg` },
  { title: "Versatile Application Support", copy: moduleCopy, icon: `${intelligentPath}icon-2.svg` },
  { title: "One Platform. Unlimited Possibilities", copy: moduleCopy, icon: `${intelligentPath}icon-3.svg` },
];

export const intelligentAutomationImage = `${intelligentPath}image-1.png`;

// Placeholder answers until final FAQ copy is provided.
export const solutionsFaqs = [
  {
    question: "How long does a typical deployment take?",
    answer:
      "Most deployments go live within 4 to 8 weeks. Timelines depend on facility size, the number of robots, and the level of system integration required. Our team shares a detailed plan covering site survey, mapping, testing, and go-live after the initial assessment.",
  },
  {
    question:
      "Do the robots need dedicated infrastructure like tape or reflectors on the floor?",
    answer:
      "No. ANSCER AMRs use natural-feature navigation built on LiDAR and sensor fusion, so they map your existing facility without magnetic tape, reflectors, or floor markings. AGV Series robots use QR-code guidance, which needs only lightweight floor markers.",
  },
  {
    question: "How long does it take to set up an ANSCER Robotic?",
    answer:
      "A single robot can be mapped, configured, and running its first missions within a few days. Wider rollouts with multiple robots and WMS, MES, or ERP integration are phased so your operations keep running throughout setup.",
  },
  {
    question: "What happens if a robot goes down mid-shift?",
    answer:
      "The fleet manager automatically reassigns pending tasks to available robots, keeping material flowing. Our in-house support team monitors issues remotely and coordinates on-site maintenance when needed to restore the robot quickly.",
  },
  {
    question: "What industries can benefit from ANSCER robotics solutions?",
    answer:
      "ANSCER solutions serve manufacturing, warehousing, automotive, electronics, FMCG, pharmaceuticals, and third-party logistics, automating pallet movement, line feeding, put-away, staging, and outbound operations.",
  },
];
