"use client";

import { useState, type FormEvent } from "react";

import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from "@/components/ui/dialog";

const fieldClassName =
  "mt-2 h-11 w-full rounded-md border border-slate-300 bg-white px-3 text-sm text-[#011f40] outline-none transition placeholder:text-slate-400 focus:border-[#005ead] focus:ring-2 focus:ring-[#005ead]/20";

type FormErrors = Partial<{
  firstName: string;
  lastName: string;
  email: string;
  company: string;
  contactNumber: string;
}>;

function getFieldValue(formData: FormData, name: string) {
  return String(formData.get(name) ?? "").trim();
}

function validatePhoneNumber(value: string) {
  const digits = value.replace(/\D/g, "");

  if (!/^[+\d][\d()+.\-\s]*$/.test(value) || digits.length !== 10) {
    return "Enter a valid phone number.";
  }

  return "";
}

export function ProductProfileRequestDialog({
  open,
  onOpenChange,
  productTitle,
  productProfileUrl,
}: {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  productTitle: string;
  productProfileUrl: string;
}) {
  const [errors, setErrors] = useState<FormErrors>({});

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const formElement = event.currentTarget;

    const formData = new FormData(formElement);
    const nextErrors: FormErrors = {};

    const firstName = getFieldValue(formData, "firstName");
    const lastName = getFieldValue(formData, "lastName");
    const email = getFieldValue(formData, "email");
    const company = getFieldValue(formData, "company");
    const contactNumber = getFieldValue(formData, "contactNumber");

    // --- 1. Client-Side Validations ---
    if (!firstName) nextErrors.firstName = "First name is required.";
    if (!lastName) nextErrors.lastName = "Last name is required.";
    
    if (!email) {
      nextErrors.email = "Work email address is required.";
    } else if (!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)) {
      nextErrors.email = "Enter a valid email address.";
    }

    if (!company) nextErrors.company = "Company name is required.";

    if (contactNumber) {
      const phoneError = validatePhoneNumber(contactNumber);
      if (phoneError) nextErrors.contactNumber = phoneError;
    }

    setErrors(nextErrors);

    if (Object.keys(nextErrors).length > 0) {
      return;
    }

    // --- 2. Disable Submit Button to Prevent Double Submissions ---
    // Adjust the selector if your submit button class differs
    const submitBtn = formElement.querySelector('.formsubmit') as HTMLButtonElement | null;
    if (submitBtn) submitBtn.disabled = true;

    try {
      // --- 3. Map Fields & Append Zoho Hidden Configurations ---
      const zohoFormData = new FormData();

      // Map your React state names to Zoho's standard field names
      zohoFormData.append("First Name", firstName);
      zohoFormData.append("Last Name", lastName);
      zohoFormData.append("Email", email);
      zohoFormData.append("Phone", contactNumber); 
      zohoFormData.append("Company", company); // Zoho default for job title is often 'Designation'
      
      // CRITICAL: You must append the hidden configuration fields generated by your specific Zoho Form setup.
      // Replace these values with the hidden inputs found in the HTML snippet Zoho provided you.
      zohoFormData.append("xnQsjsdp", "75f788ee9231443042f34541a6ff1b22fa14f081a9bfaea53905f00212778bbd");
      zohoFormData.append("xmIwtLD", "e62703cdfe64d795e0c7991b92db8d5e348e9fc219eb21caddbaeaca6563601dc10c99868b1fc0f7b68d9a6beb6ea3a9");
      zohoFormData.append("actionType", "TGVhZHM=");
      zohoFormData.append("returnURL", "");
      zohoFormData.append("zc_gad", "");
      zohoFormData.append("LEADCF1", productTitle);
      zohoFormData.append("LEADCF9", "-None-");
      zohoFormData.append("Lead Source", "ContactForm_website_product_page");

      // Optional: Handle track service parameter from url if used by your setup
      const urlParams = new URLSearchParams(window.location.search);
      if (urlParams.has("service") && urlParams.get("service") === "smarturl") {
        zohoFormData.append("service", urlParams.get("service") || "");
      }

      // --- 4. Submit to Zoho CRM API ---
      const response = await fetch("https://crm.zoho.com/crm/WebToLeadForm", {
        method: "POST",
        body: zohoFormData,
        cache: "no-cache",
      });

      if (!response.ok) throw new Error("Network response was not ok");

      const contentType = response.headers.get("Content-Type") || "";
      const data = contentType.includes("application/json") ? await response.json() : await response.text();

      // --- 5. Handle Zoho's Response Context ---
      if (typeof data === "object") {
        // Check if captcha failed (based on Zoho script handling)
        if (data.invalidCaptcha && data.invalidCaptcha === "true") {
          alert(data.actionvalue || "Captcha verification failed.");
          if (submitBtn) submitBtn.disabled = false;
          return;
        }
        
        // Handle Success Redirects or Thank you screens
        if (data.actionsubmit === "redirect_url" || data.actionsubmit === "thankyou_page") {
          // Run any custom analytics tracks if available: _wfa_track.wfa_post_submit(event);
          window.location.assign(data.redirectUrl);
          return;
        }
      }

      // --- 6. Success Fallback Flow (Open Product Profile & Reset) ---
      window.open(productProfileUrl, "_blank", "noopener,noreferrer");
      onOpenChange(false);
      formElement.reset();

    } catch (error) {
      console.error("Zoho Submission Error:", error);
      alert("An error occurred while submitting. Please try again.");
    } finally {
      if (submitBtn) submitBtn.disabled = false;
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="rounded-[24px] border border-slate-200 bg-white p-0 text-[#011f40] shadow-[0_30px_80px_rgba(0,0,0,.22)] sm:max-w-200">
        <div className="grid gap-0 md:grid-cols-1">
          <div className="p-6 sm:p-8 lg:p-10">
            <DialogHeader className="max-w-none gap-3">
              <DialogTitle className="text-[30px] font-bold leading-tight tracking-tight text-[#011f40] sm:text-[36px]">
                Request Product Profile
              </DialogTitle>
              <DialogDescription className="max-w-sm text-sm leading-6 text-slate-600 sm:text-base">
                Complete the form below and our team will send the requested
                product datasheet to your email.
              </DialogDescription>
            </DialogHeader>

            <form className="mt-8 grid grid-cols-1 gap-4" noValidate onSubmit={handleSubmit}>
              <div className="grid gap-4 sm:grid-cols-2">
                <label className="text-sm font-medium uppercase tracking-wide text-slate-700">
                  First name *
                  <input
                    name="firstName"
                    type="text"
                    autoComplete="given-name"
                    aria-invalid={Boolean(errors.firstName)}
                    aria-describedby={errors.firstName ? "firstName-error" : undefined}
                    className={fieldClassName}
                  />
                  <span id="firstName-error" className="mt-1 block min-h-4 text-xs text-red-600">
                    {errors.firstName}
                  </span>
                </label>
                <label className="text-sm font-medium uppercase tracking-wide text-slate-700">
                  Last name *
                  <input
                    name="lastName"
                    type="text"
                    autoComplete="family-name"
                    aria-invalid={Boolean(errors.lastName)}
                    aria-describedby={errors.lastName ? "lastName-error" : undefined}
                    className={fieldClassName}
                  />
                  <span id="lastName-error" className="mt-1 block min-h-4 text-xs text-red-600">
                    {errors.lastName}
                  </span>
                </label>
              </div>

              <div className="grid gap-4 sm:grid-cols-2">
                <label className="text-sm font-medium uppercase tracking-wide text-slate-700">
                  Work email address *
                  <input
                    name="email"
                    type="email"
                    autoComplete="email"
                    aria-invalid={Boolean(errors.email)}
                    aria-describedby={errors.email ? "email-error" : undefined}
                    className={fieldClassName}
                  />
                  <span id="email-error" className="mt-1 block min-h-4 text-xs text-red-600">
                    {errors.email}
                  </span>
                </label>
                <label className="text-sm font-medium uppercase tracking-wide text-slate-700">
                  Company name *
                  <input
                    name="company"
                    type="text"
                    autoComplete="organization"
                    aria-invalid={Boolean(errors.company)}
                    aria-describedby={errors.company ? "company-error" : undefined}
                    className={fieldClassName}
                  />
                  <span id="company-error" className="mt-1 block min-h-4 text-xs text-red-600">
                    {errors.company}
                  </span>
                </label>
              </div>

              <label className="text-sm font-medium uppercase tracking-wide text-slate-700">
                Contact number
                <input
                  name="contactNumber"
                  type="number"
                  autoComplete="tel"
                  aria-invalid={Boolean(errors.contactNumber)}
                  aria-describedby={errors.contactNumber ? "contactNumber-error" : undefined}
                  className={fieldClassName}
                />
                <span id="contactNumber-error" className="mt-1 block min-h-4 text-xs text-red-600">
                  {errors.contactNumber}
                </span>
              </label>

              <div className="pt-2">
                <Button
                  type="submit"
                  className="h-12 rounded-[3px] bg-[#005ead] px-6 text-[14px] font-semibold uppercase tracking-wide text-white hover:bg-[#004b8b]"
                >
                  Download
                </Button>
              </div>

              <p className="pt-2 text-sm italic text-slate-400">
                Your information will only be used to process this product profile
                request for {productTitle}.
              </p>
            </form>
          </div>
        </div>
      </DialogContent>
    </Dialog>
  );
}